config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'user#new'
  post '/signup', to: 'user#create'
  root 'posts#index'
  resources :user
  resources :sessions, only: %i[new create destroy]
  resources :posts, only: %i[new create index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :remember_token
  before_create :remember
  has_many :posts

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def update_token
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  private

  def remember
    remember_token = User.new_token
    self.remember_digest = User.digest(remember_token)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :require_login, only: %i[new create]

  def new; end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.valid?
      @post.save
      redirect_to '/posts'
    else
      flash.now[:danger] = "Title/content can't be empty"
      render 'new'
    end
  end

  def index
    @posts = Post.all
  end

  private

  def require_login
    return if logged_in?

    flash[:error] = 'You must be logged in to make/edit posts'
    redirect_to login_path
  end

  def post_params
    params.require(:post).permit(:title, :content, :user_id)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user&.authenticate(params[:session][:password])
      log_in @user
      remember_cookies @user
      redirect_to '/posts'
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/user_controller.rb
# frozen_string_literal: true

class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      remember_cookies @user
      flash.now[:info] = 'Account successfully created!'
      redirect_to root_url
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget_cookies(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])

    elsif cookies.signed[:user_id]
      user = User.find_by(id: cookies.signed[:user_id])
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def remember_cookies(user)
    user.update_token
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget_cookies(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/views/layouts/_header.html.erb
<h1 class="text-danger">
  <% if logged_in? %><%= current_user.name %>'s<% end %> Clubhouse
</h1>

<div class="main-menu">
  <div>
    <%= link_to "Home", root_path %>
    <% if logged_in? %>
      <%= link_to "New post", "posts/new" %>
    <% end %>
  </div>
  <div>
    <% if logged_in? %>
      <%= link_to "Log out", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Sign Up", signup_path %>
      <%= link_to "Log In", login_path %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h2 class="text-danger">Posts</h2>
<table class="container">
  <thead>
    <tr class="row">
      <th class="col-3">Title</th>
      <th class="col-3">Content</th>
      <% if logged_in? %>
        <th class="col-3">User</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr class="row">
        <td class="col-3 "><%= post.title %></td>
        <td class="col-3"><%= post.content %></td>
        <% if logged_in? %>
            <td class="col-3"><%= User.find(post.user_id).name %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<div class="container bg-dark">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(:post, :url => { :action => :create } ) do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>

        <%= f.label :content %>
        <%= f.text_area :content, class: 'form-control' %>

        <%= f.submit "Submit", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/user/new.html.erb
<div class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(:user, :url => { :action => :create }) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Sign up", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>